# # Numpy

## - 생성

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [21]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## - 변형

In [2]:
int_matrix = np.arange(10).reshape(2, 5)
int_matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
int_matrix.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [4]:
int_matrix.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## - 랜덤

In [8]:
np.random.rand(2, 3)

array([[0.00658445, 0.30453248, 0.9755026 ],
       [0.10435814, 0.99955453, 0.3651472 ]])

In [9]:
np.random.randn(2, 3)

array([[-1.56885409,  0.88898145, -1.88359211],
       [ 0.65884204,  0.8758565 , -0.87683842]])

In [10]:
np.random.randint(0, 10, 5)

array([9, 8, 6, 8, 8])

## - 선택

In [42]:
int_list = [[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]]
int_list

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [43]:
int_matrix = np.array(int_list)
int_matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
int_matrix[0]

array([0, 1, 2, 3, 4])

In [44]:
int_list[0, 2]

TypeError: list indices must be integers or slices, not tuple

In [29]:
int_matrix[0][2]
int_matrix[0, 2]     # numpy만

2

In [30]:
int_matrix[:, 2]

array([2, 7])

In [32]:
int_matrix[1, 1:3]

array([6, 7])

In [45]:
int_list[int_list > 3]

TypeError: '>' not supported between instances of 'list' and 'int'

In [41]:
int_matrix[int_matrix > 3]     # numpy만

array([4, 5, 6, 7, 8, 9])

In [34]:
int_matrix[int_matrix > 3] = 0
int_matrix

array([[0, 1, 2, 3, 0],
       [0, 0, 0, 0, 0]])

In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
names

array(['Bob', 'Joe', 'Will', 'Bob'], dtype='<U4')

In [49]:
names == 'Bob'

array([ True, False, False,  True])

In [48]:
names[names != 'Bob']

array(['Joe', 'Will'], dtype='<U4')